version: "3.8"

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: product_manager
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mariadb-admin", "-u", "root", "-p123", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"

volumes:
  db_data: