spring:
  datasource:
    url: jdbc:mariadb://db:3306/product_manager
    username: root
    password: 123
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration